# Generated by Django 5.0.3 on 2024-04-11 08:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bilan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DATPortofolio',
            fields=[
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dat_portofolio', to='bilan.bilan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DAT',
            fields=[
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dat_client', models.CharField(max_length=100)),
                ('dat_outstanding', models.FloatField()),
                ('dat_value_date', models.DateField()),
                ('dat_due_date', models.DateField()),
                ('dat_period', models.CharField(choices=[('M', 'Monthly'), ('T', 'Trimestrial'), ('S', 'Semestrial'), ('A', 'Annual')], default=0, max_length=1)),
                ('dat_rate', models.FloatField()),
                ('dat_type', models.CharField(choices=[(0, 'Type 1'), (1, 'Type 2')], default=0, max_length=100)),
                ('dat_interest', models.FloatField()),
                ('dat_cashflows', models.JSONField(default=dict)),
                ('dat_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dat_portofolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dat', to='dat.datportofolio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
