# Generated by Django 5.0.3 on 2024-06-27 08:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapOperation',
            fields=[
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_duration', models.FloatField(default=0.0)),
                ('offer_quantity', models.IntegerField(default=0)),
                ('offer_return', models.FloatField(default=0.0)),
                ('offer_country', models.CharField(blank=True, max_length=100, null=True)),
                ('validity', models.DateField()),
                ('demand_duration', models.FloatField(default=0.0)),
                ('demand_quantity', models.IntegerField(default=0)),
                ('demand_return', models.FloatField(default=0.0)),
                ('demand_country', models.CharField(blank=True, max_length=100, null=True)),
                ('is_simulated', models.BooleanField(default=False)),
                ('is_swaped', models.BooleanField(default=False)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alm.bond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SwapProposition',
            fields=[
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='P', max_length=1)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='swaps.swapoperation')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alm.bond')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
