# Generated by Django 5.0.3 on 2024-05-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swaps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swapoperation',
            old_name='bond',
            new_name='offer',
        ),
        migrations.RemoveField(
            model_name='swapoperation',
            name='attractive',
        ),
        migrations.AddField(
            model_name='swapoperation',
            name='demand_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='swapoperation',
            name='demand_duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='swapoperation',
            name='demand_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='swapoperation',
            name='demand_return',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='swapoperation',
            name='offer_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='swapoperation',
            name='offer_duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='swapoperation',
            name='offer_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='swapoperation',
            name='offer_return',
            field=models.FloatField(default=0.0),
        ),
    ]
