# Generated by Django 5.0.3 on 2024-04-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminbond',
            name='space',
            field=models.CharField(choices=[('CEDEAO', "Communauté Economique des Etats de l'Afrique de l'Ouest (CEDEAO)"), ('CEMAC', "Communauté économique et monétaire de l'Afrique centrale (CEMAC)"), ('COMORES', 'Union des Comores (UC)'), ('UEAC', "Union des États de l'Afrique centrale (UEAC)"), ('UA', 'Union africaine (UA)')], default='UEMOA', max_length=255),
        ),
    ]
