# Generated by Django 5.0.3 on 2024-04-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_alter_adminbond_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminbond',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
