# Generated by Django 5.0.3 on 2024-04-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_alter_adminbond_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminbond',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
