# Generated by Django 5.0.3 on 2024-04-11 08:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bilan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OPInjectionPortofolio',
            fields=[
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_injection_portofolio', to='bilan.bilan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OPInjection',
            fields=[
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('op_injection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('op_injection_lender', models.CharField(max_length=100)),
                ('op_injection_outstanding', models.FloatField()),
                ('op_injection_value_date', models.DateField()),
                ('op_injection_due_date', models.DateField()),
                ('op_injection_rate', models.FloatField()),
                ('op_injection_type', models.IntegerField(choices=[(0, "Opération d'injection liquidité de maturité longue"), (1, "Opération principal d'injection de liquidité")], default=0)),
                ('op_injection_interest', models.FloatField()),
                ('op_injection_cashflows', models.JSONField(default=dict)),
                ('op_injection_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('op_injection_portofolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op_injection', to='op_injection.opinjectionportofolio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
