# Generated by Django 5.0.3 on 2024-05-07 09:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backoffice', '0001_initial'),
        ('bilan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BondPortofolio',
            fields=[
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_portofolio', to='bilan.bilan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outstanding', models.FloatField()),
                ('issuer', models.CharField(max_length=100)),
                ('value_date', models.DateField()),
                ('due_date', models.DateField()),
                ('facial_rate', models.FloatField()),
                ('refund', models.CharField(choices=[('IF', 'In Fine'), ('AC', 'Constant Amortissable'), ('ACD', 'Differed Constant Amortissable')], default='IF', max_length=5)),
                ('differed', models.IntegerField()),
                ('refinancing', models.CharField(max_length=100)),
                ('guarantee', models.CharField(max_length=100)),
                ('total_number', models.IntegerField()),
                ('number_available', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('period', models.CharField(choices=[('T', 'Trimestrial'), ('S', 'Semestrial'), ('A', 'Annual')], default='A', max_length=1)),
                ('cotation', models.CharField(max_length=50)),
                ('reference_value', models.FloatField(default=0)),
                ('annual_coupon', models.FloatField(blank=True, null=True)),
                ('cashflows', models.JSONField(default=dict)),
                ('valorisations', models.JSONField(default=dict)),
                ('duration_macaulay', models.JSONField(default=dict)),
                ('isin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.adminbond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('portofolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond', to='alm.bondportofolio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
