# Generated by Django 5.0.3 on 2024-04-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bond',
            old_name='reference_course',
            new_name='reference_value',
        ),
    ]
