# Generated by Django 5.0.3 on 2024-05-07 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm', '0001_initial'),
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='isin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alm_bond', to='backoffice.adminbond'),
        ),
    ]
