# Generated by Django 5.0.3 on 2024-07-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondportofolio',
            name='start',
            field=models.CharField(choices=[('0', 'Blank'), ('1', 'Active Portofolio')], default='0', max_length=1),
        ),
    ]
