# Generated by Django 5.0.3 on 2024-07-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm', '0002_bondportofolio_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondportofolio',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
