# Generated by Django 5.0.3 on 2024-04-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm', '0003_alter_bond_guarantee_alter_bond_reference_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='cashflows',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='bond',
            name='duration_macaulay',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='bond',
            name='valorisations',
            field=models.JSONField(),
        ),
    ]
