# Generated by Django 5.0.3 on 2024-04-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alm', '0004_alter_bond_cashflows_alter_bond_duration_macaulay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='cashflows',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='bond',
            name='duration_macaulay',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='bond',
            name='valorisations',
            field=models.JSONField(default=dict),
        ),
    ]
