# Generated by Django 5.0.3 on 2024-04-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spreads', '0002_spreadoperation_spreadproposition_delete_spread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadoperation',
            name='attractive',
        ),
    ]
